#!/usr/bin/env python3
# -*- coding: utf-8 -*-


def main():
    pass

if __name__ == '__main__':
    main()
    import timeit
    print(timeit.timeit("main()", setup="from __main__ import main",
                        number=10000))
