#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pprint import pprint

def main():
    pass

if __name__ == "__main__":
    main()
    from timeit import timeit
    print(timeit("main()", setup="from __main__ import main", number=10000))
